language: node_js
node_js:
  - 16.14.2
script:
  -"npm run build"
  -"npm run test:nowatch"
before_deploy:
  - rvm requirements
  - rvm install 2.6
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app:book-store-react-client